/// Flutter icons PatternIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PatternIcons
///      fonts:
///       - asset: fonts/PatternIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PatternIcons {
  PatternIcons._();

  static const _kFontFam = 'PatternIcons';
  static const String? _kFontPkg = null;

  static const IconData box = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blinker = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glider = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
